---
output:
  pdf_document: default
  html_document: default
---

# Designing the Study {#designstudy}

<!-- https://voxeu.org/article/simple-rules-designing-economic-experiments
-->
<!-- https://www.questionpro.com/blog/empirical-research/
-->

## Basic steps in designing your study

We have arrived at the heart of your research study to specify how you will empirically test your hypothesis. We focus on study designs make use of secondary data with the aim to identify the magnitude of effects of causal relationships between a variable of interest $X$ and a certain outcome $Y$. Note that there is extensive literature and guidance to perform causal inference, some of which we guide you to below. We will highlight the most important elements and point to the relevant resources.

You have chosen your research questions and formulated a hypothesis. You also have collected and reviewed all the relevant literature on your topic. Now, you need to decide on your research design. Are you planning to uncover associations, or do you want to examine a causal relationship between your variables of interest [@pearl_causality_2009;@pearl_causal_2016]? To translate direct observations in data to investigate cause-and-effect relationships, you will need to rely on a workable model that describes the elements reflected by your hypothesis. For that reason, it is recommended that you first describe the causal structures of the elements that you are studying, including any other observed or unobserved structures that may disturb the cause-and-effect relationship under investigation.

The design of your study will depend on the causal model that suggests which effects are estimable, given that there are suitable data to empirically identify the effect. Consider that you describe cause-and-effect relationship first, assess how it is estimable (that means that you ask the question "Can you infer a causal effect from your data?") and then investigate the effect by direct observations using secondary data. The alternative is to start out with a regression estimated effect and then investigate whether it has a causal interpretation.

Consider the subsequent steps as an iterative process, allowing that not all data you may need to estimate effects of your causal model will be readily available. Some elements will remain unobserved.


### Clarify your study goal: association, causation, counterfactuals

(see Pearl (2009) on the *"ladder of causality"*)


### Develop a causal model and identify estimable effects

Once you have made this decision, you should specify a causal model that describes the relationships between the elements that you are studying. This causal model will help to identify empirical model by defining your main relationship of interest. 

You need to specify your

- main outcomes variable of interest ($X$)
- main independent variable of interest ($Y$)
- other independent variables (confounders of the effect of $X$ on $Y$), that means any additional $Z$'s
- unobserved variables ($U$)

For better visualization, you may plot the corresponding [directed acyclic graph](https://cran.r-project.org/web/packages/ggdag/vignettes/intro-to-dags.html) to describe the relationships between your variable of interest and any confounding variable. It is recommended to do this step before data collection. That way, you avoid collection of data that may not be needed. You also avoid forgetting variables that are necessary to for causal effect identification. And you may [check for so-called bad controls](https://ftp.cs.ucla.edu/pub/stat_ser/r493.pdf) that may bias your estimates.




### Develop the empirical strategy to investigate causal effects

Potential outcomes framework notation

Write down your estimate, your estimand, notation



After you have specified your causal model, ask yourself how you can capture the causal relationship between $X$ and $Y$. In other words, can you apply an appropriate research design that can accommodate you in determining causality with the data at hand? Following the classification by @matthay_alternative_2020, that means by performing a


- Randomized Controlled Trial (RCT): this would be the ideal world case where we could randomize treatments to study effect

Secondary data will not allow performing a RCT as you will not be able to randomly assign subjects, such that you need to run a quasi-experiment to identify treatment effects using a

- Confounder Control Study

  - Regression adjustment
  - Matching Techniques
  - Two-way fixed-effects (TWFE) panel regressions

- Instruments

  - Regression discontinuity design (RDD)
  - Difference-in-difference (DiD) analysis
  - Instrumental variable (IV) approach

- Structural equation models


Think about what type of treatment effect you are investigating in your causal analysis. The treatment effect is the average (across the population or across some subpopulation) of the change in outcome ($Y$) that results from a change in a covariate (the treatment $X$) [@lewbel_identification_2019].

Common types of treatment effect parameters are

- average treatment effects (ATE)
- average treatment effects on the treated (ATT)
- marginal treatment effects (MTE)
- local average treatment effects (LATE)
- quantile treatment effects (QTE)

<!-- include a note on ML and causal ML -->



### Investigate suitable source data

You need to find and collect suitable data to populate your causal model. This might take some time, and not all of the variables can be found in one dataset. You might frequently need to collect and combine a few different data sources. When searching for the data sources, you can turn to already existing datasets specifically designed for scientific use, for example surveys (NAMCS, CPS, NLSY, HILDA, RLMS HSE, KiGGS); panels (for example GSOEP, SHARE, HRS, ELSA); censuses (e.g. Microcensus). [INCLUDE LINKS]

Some data are available from statistical offices (Eurostat in the European Union, DESTATIS for Germany), private companies (health insurances), Social Media and App based data (Mappiness, Fitbit, Facebook, Twitter, WayBetter) or governmental and non-governmental institutions (EMA, FDA, BfARM). Sometimes you have to hand-collect and digitize the necessary data, for example from historical documents, data from governmental and non-governmental agencies, commercial providers and library search engines, archives; download statistical tables from INKAR's or Unemployment Agency's websites. Therefore, you need to plan whether and how these can be accessed and how much time is needed for extraction. Consider automated tools like scraping.

You need to decide on what aggregation level you need to conduct your analysis to estimate the cause-and-effect relationships postulated, for example individual (patient, student), organization (hopstial), regional (country, state). Given that, you need to identify appropriate data sources that contain your variables of interest at the given aggregation level.


## Resources box


### Key terminology in causal inference based on @matthay_alternative_2020

- **Causal model**: A description, most often expressed as a system of equations or a diagram, of a researcher’s assumptions about hypothesized known causal relationships among variables relevant to a particular research question.
- **Treatment, exposure, or independent variable**: The explanatory variable of interest in a study. Some also describe this as the “right-hand-side variable”.
- **Outcome, dependent variable, or left-hand-side variable**: The causal effect of interest in a research study is the impact of an exposure(s) on an outcome(s).
- **Potential outcome**: The outcome that an individual (or other unit of analysis, such as family or neighborhood) would experience if his/her treatment takes any particular value. Each individual is conceptualized as having a potential outcome for each possible treatment value. Potential outcomes are sometimes referred to as counterfactual outcomes.
- **Exogenous versus endogenous variables**: These terms are common in economics, where a variable is described as exogenous if its values are not determined by other variables in the causal model. The variable is called endogenous if it is influenced by other variables in the causal model. If a third variable influences both the exposure and outcome, this implies the exposure is endogenous.


### Openly-available textbooks and resources on econometrics with a causal inference focus

- [Causal Inference: The Mixtape](https://mixtape.scunning.com/)  by [Scott Cunningham](http://www.scunning.com/)
- [What If](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) by Jamie Robin and Miguel Hernan
- [The Effect: An Introduction to Research Design and Causality](http://nickchk.com/causalitybook.html) by [Nick Huntington-Klein](http://nickchk.com/)
- [How Do We Know if a Program Made a Difference? A Guide to Statistical Methods for Program Impact Evaluation](https://www.measureevaluation.org/resources/publications/ms-14-87-en.html) by MEASURE Evaluation
- [Open Source Economics Basics to microeconometric methods](https://ose-data-science.readthedocs.io/en/latest/lectures/index.html)
- [Introduction to Econometrics using R](https://www.econometrics-with-r.org/) by [Christoph Hanck](https://www.oek.wiwi.uni-due.de/en/team/christoph-hanck/)
- [Econometrics](https://www.ssc.wisc.edu/~bhansen/econometrics/) by [Bruce E. Hansen](https://www.ssc.wisc.edu/~bhansen/)
- [Mastering Econometrics](https://mru.org/mastering-econometrics) by [Joshua Angrist](https://economics.mit.edu/faculty/angrist)
- [Differences-in-Difference design, Health Care Policy Science Lab](https://diff.healthpolicydatascience.org/)
- [Statistical Tools for Causal Inference](https://chabefer.github.io/STCI/) by the SKY Community



### Drawing Causal Diagrams


- A tool to draw Directed Acyclic Graphs (DAGs) is [DAGitty](http://www.dagitty.net/)

### Replication examples

- [Replication of "Mostly Harmless Econometrics" in Stata, R, Python and Julia](https://github.com/vikjam/mostly-harmless-replication) 



## Example: Hellerstein (1998)

With the identified research question and the hypothesis that physicians are more likely to prescribe generics to patients who do not have insurance coverage for prescription pharmaceuticals at hand an observational, retrospective analysis of secondary data, including patient and physician characteristics is needed. The goal of the analysis is to identify a causal effect of the patient's insurance status (independent variable $X$) on the prescription of a generic over a trade-name drug (dependent variable, $Y$). As the prescription decision of the physician is prone to involve information imperfections and agency problems, the empirical model needs to control for physician specific effects among other possible influencing factors.

<!--Write down regression equation and estimand-->

The confounder control study design chosen by Hellerstein (1998) applies a random effects probit specification at physician level. This includes the variable of interest (estimate), a binary variable, which indicates whether a patient got a trade-name or a generic drug prescribed. The estimate takes the value 1 if a generic drug or the value 0 if a trade-name drug was prescribed. Of interest is the causal effect of the patients different insurance types. Those include Medicare, Medicaid, HMO/prepaid and private insurance. Other independent variables included in the analysis for the purpose of reducing possible bias are the drug class, patient characteristics (age, gender, race), if the physician is a specialist, the region and the averages of patient characteristics per physician. The choice of covariates to be included in a study depends on the study design, the relevant literature in the field and on possible restriction by the underlying data. Sometimes a certain creativity is needed, to use the data at hand in such way to be able to account for possible bias. An example from Hellerstein's (1998) study design is the explicit need to include prices into the empirical analysis. Though prices are not given in the data used, they were accounted for by including drug class dummy variables assuming that prices vary across different drug classes. This way, though we cannot identify the effect of the individual prices directly, we account for possible bias of the different prices of drug classes.  

