--- 
title: "A concise guide to reproducible research using secondary data"
author: "Maryna Ivets, Eva Goetjes, Kai Miele, Katharina Blankart"
date: "`r Sys.Date()`"
output: pdf_document
description: Data Science Campus - A study guide for reproducible research using secondary (health care) data
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---


# A study guide to empirical research in economics and management using secondary data {-}

## Objective {-}

The objective of this study guide is to provide a resource to graduate students, early career PhD candidates and researchers performing applied empirical research in economics and management sciences. The pratical application is in the field of analysis of health care markets using secondary data. Many textbook examples use readily available datasets for analysis of econometric problems. For students aiming to conduct research by generating their own analysis dataset, important steps that lead to a final analysis dataset are missing. Besides, many resources focus on labor economics problems. Resources that consider processing and generating secondary data are scarce. One reason is that often these data sources are subject to confientiality and data protection issues and as such cannot be made easily available.

This guide explains the 5 major steps needed to create a reproducible research project. We introduce important terminology, highlight the relevant tasks to be performed, and provide key resources in the form of text books and websites available via open access. We provide a concise guide that users can easily access when starting academic research. Each section takes about 10-15 minutes to read. We do not cover any specific data science or econometric method, but point to the relevant resources. Users of this guide should have basic knowledge in statistics, econometrics and program evaluation, as well as basic knowledge in statistical packages such as R or Stata. For the study guide to be of most benefit, readers should have background knowledge and a research idea in mind while reading.

## Learning objectives {-}

The goal is to set up and carry out a data science project using secondary data. Students will learn all steps starting with hypothesis formulation, data generation and analysis, and presentation of empirical results.

After reading and applying the principles introduced in this study guide, you will be able to:

1. Recognize the features of using secondary (health care) data in empirical research.
2. Execute the steps of a reproducible research project.
3. Be able to implement an empirical research project.
4. Recall the steps taken to execute a reproducible research project using secondary data.

## Structure of the study guide {-}

The study guide consists of five chapters that include the essential steps of a reproducible research project. Each step of reproducible research is covered in three parts.
  
1. An introduction to the basics concepts and key terminology. 
2. A resources box that includes reference material how to perform this step including main textbooks and references to current web resources. We will emphasize open source materials.
3. A showcase example of an empirical project reproduced based on the article: *Hellerstein, Judith K. 1998. “The Importance of the Physician in the Generic versus Trade-Name Prescription Decision.” The RAND Journal of Economics 29 (1): 108–36. https://doi.org/10.2307/2555818*.


## This is a living document {-}

How can you contribute to this study guide? Best practices how to perform reproducible research are constantly developing. We aim to keep resources up to date. If you come across a good open access resource or suggestions for improvement, please share it by emailing to: elearning@fosteropenscience.eu

# Acknowledgements {-}

The authors thank Christoph Kronenberg for comments and suggestions. 

Development of this resource has received funding by [*Data Literacy Education.nrw*](https://www.dh.nrw/aktuelles/ausschreibung). It is part of the [DataCampus project of the University of Duisburg-Essen](https://www.uni-due.de/ub/datacampus/index.php).

<!--## Open License and Credits

This concise guide to reproducible research using secondary data is written as an Open Educational Resource to enable you to use this book in the best possible way. This work is therefore made available under Creative Commons Public Domain Dedication (CC0 1.0 Universal). You do not have to ask us permission to re-use and copy information from this handbook. Feel free to use information from the content section for your training slides or images that seem fitting in your training. Take note that some materials cited in this book might be copyright protected. If so, this will be indicated in the text. Please consider citing the handbook when using the content.

We have tried to acknowledge all of our sources. If for some reason we have forgotten to provide you with proper credits it has not been done with malicious intent. Feel free to contact us at elearning@fosteropenscience.eu for any corrections.-->

	    	
